language: php
php:
  - '7.1'

script:
  - composer install --dev --no-interaction
  - ./vendor/bin/phpunit

after_success:
  - test $TRAVIS_BRANCH = "master" && composer require satooshi/php-coveralls && travis_retry php vendor/bin/coveralls